apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: azure-openai
  namespace: kagent
spec:
  provider: AzureOpenAI
  model: ${OPENAI_MODEL}
  apiKeySecret: kagent-azure-openai
  apiKeySecretKey: AZUREOPENAI_API_KEY
  azureOpenAI:
    azureEndpoint: ${OPENAI_ENDPOINT}
    azureDeployment: ${OPENAI_DEPLOYMENT}
    apiVersion: "2024-10-21"
