controller:
  grpc:
    reflection: false

  substrate:
    enabled: true

    ateApiEndpoint: dns:///api.ate-system.svc:443

    atenetRouterURL: http://atenet-router.ate-system.svc:80

    defaultWorkerPool:
      name: kagent-default

substrateWorkerPool:
  create: true

  replicas: 2

  workerImage: "ghcr.io/kagent-dev/substrate/ateom-gvisor:v0.2.0-beta5"